<?php 
use Magento\Framework\App\Action\Action; 
?>
<script type="text/x-magento-init">
             {
                ".owl-carousel":
                    {
                        "Bss_Bestseller/js/carousel": {
                            "count" : <?php echo count($this->getBestSellerProduct()); ?>
                        }
                    },
                "[data-role=tocart-form]": 
                    {
                        "catalogAddToCart": {}
                    }
             }
</script>
<h1>New Arrival</h1>
<div class="owl-carousel owl-theme">
<?php
$productCollection = $block->getProductCollection();
foreach ($productCollection as $product) {
 
?>
	<div class="item">
        <a href="<?php echo $product->getProductUrl();?>">
            <img src="<?php echo 'http://localhost/magento221/pub/media/catalog/product'.$product->getImage();?>"><?php echo $product->getName(); ?>
        </a>
         <div class="product-item-actions">
            <div class="actions-primary">
                <?php $postParams = $block->getAddToCartPostParams($product); ?>
                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                        <?php echo $block->getBlockHtml('formkey')?>
                        <?php $storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface'); ?>
                        <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                class="action tocart primary">
                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                        </button>
                    </form>
            </div>
            <div class="actions-secondary">
                <div class="product-reviews-summary short">
                    <div class="rating-summary">
                        <span class="label"><span>Rating:</span></span>
                            <div class="rating-result">
                                <span style="width:<?php echo $block->getRatingReviews($product); ?>%"><span><?php echo $block->getRatingReviews($product); ?>%</span></span>
                            </div>
                    </div>
                    <div class="reviews-actions">
                        <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>" class="action view"><?php echo $block->getRatingSummary($product) . ' ' . 'review'; ?></a>
                    </div>
                </div>
                <div class="product-reviews-summary short">
                    <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>" class="action view"><?php echo 'Be first review this product'; ?></a>
                </div>
                    
            </div>
        </div>
    </div>
<?php
}
?>
</div>
<h1>Bestseller</h1>
<div class="owl-carousel owl-theme">
<?php
$productCol = $block->getBestSellerData();
foreach ($productCol as $product) {
?>
    <div class="item">
        <a href="<?php echo $product->getProductUrl();?>">
            <img src="<?php echo 'http://localhost/magento221/pub/media/catalog/product'.$product->getImage();?>"><?php echo $product->getName(); ?>
        </a>
        <div class="product-item-actions">
            <div class="actions-primary">
                <?php $postParams = $block->getAddToCartPostParams($product); ?>
                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                        <?php echo $block->getBlockHtml('formkey')?>
                        <?php $storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface'); ?>
                        <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                class="action tocart primary">
                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                        </button>
                    </form>
            </div>
            <div class="actions-secondary">
                <div class="product-reviews-summary short">
                    <div class="rating-summary">
                        <span class="label"><span>Rating:</span></span>
                        <div class="rating-result">
                            <span style="width:<?php echo $block->getRatingReviews($product); ?>%"><span><?php echo $block->getRatingReviews($product); ?>%</span></span>
                        </div>
                    </div>
                    <div class="reviews-actions">
                        <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>" class="action view"><?php echo $block->getRatingSummary($product) . ' ' . 'review'; ?></a>
                    </div>
                </div>
                <div class="product-reviews-summary short">
                    <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>" class="action view"><?php echo 'Be first review this product'; ?></a>
                </div>
            </div>
        </div>
    </div>
<?php
}
?>
</div>
<script>
    (function  () {
        require(["jquery","Bss_Bestseller/js/owl.carousel"],function($) {
            jQuery(document).ready(function() {
                jQuery(".owl-carousel").owlCarousel({
                    loop:true,
                    margin:10,
                    nav:true,
                    responsive:{
                        0:{
                            items:1
                        },
                        1000:{
                            items:5
                        },
                    }
                });
            });
        });
    })();
</script>
